/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_minecraft_server_c_libnbt_NBT */

#ifndef _Included_net_minecraft_server_c_libnbt_NBT
#define _Included_net_minecraft_server_c_libnbt_NBT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_parse
 * Signature: (Ljava/lang/String;I)Lnet/minecraft/server/c/libnbt/NBTTag;
 */
JNIEXPORT jobject JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1parse
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_write
 * Signature: (Ljava/lang/String;JI)V
 */
JNIEXPORT void JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1write
  (JNIEnv *, jclass, jstring, jlong, jint);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_new_tag_byte
 * Signature: (B)Lnet/minecraft/server/c/libnbt/NBTTag;
 */
JNIEXPORT jobject JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1new_1tag_1byte
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_new_tag_short
 * Signature: (S)Lnet/minecraft/server/c/libnbt/NBTTag;
 */
JNIEXPORT jobject JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1new_1tag_1short
  (JNIEnv *, jclass, jshort);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_new_tag_int
 * Signature: (I)Lnet/minecraft/server/c/libnbt/NBTTag;
 */
JNIEXPORT jobject JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1new_1tag_1int
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_new_tag_long
 * Signature: (J)Lnet/minecraft/server/c/libnbt/NBTTag;
 */
JNIEXPORT jobject JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1new_1tag_1long
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_new_tag_float
 * Signature: (F)Lnet/minecraft/server/c/libnbt/NBTTag;
 */
JNIEXPORT jobject JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1new_1tag_1float
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_new_tag_double
 * Signature: (D)Lnet/minecraft/server/c/libnbt/NBTTag;
 */
JNIEXPORT jobject JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1new_1tag_1double
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_new_tag_byte_array
 * Signature: ([BJ)Lnet/minecraft/server/c/libnbt/NBTTag;
 */
JNIEXPORT jobject JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1new_1tag_1byte_1array
  (JNIEnv *, jclass, jbyteArray, jlong);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_new_tag_string
 * Signature: (Ljava/lang/String;)Lnet/minecraft/server/c/libnbt/NBTTag;
 */
JNIEXPORT jobject JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1new_1tag_1string
  (JNIEnv *, jclass, jstring);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_new_tag_string0
 * Signature: (Ljava/lang/String;J)Lnet/minecraft/server/c/libnbt/NBTTag;
 */
JNIEXPORT jobject JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1new_1tag_1string0
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_new_tag_list
 * Signature: (I)Lnet/minecraft/server/c/libnbt/NBTTag;
 */
JNIEXPORT jobject JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1new_1tag_1list
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_new_tag_compound
 * Signature: ()Lnet/minecraft/server/c/libnbt/NBTTag;
 */
JNIEXPORT jobject JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1new_1tag_1compound
  (JNIEnv *, jclass);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_new_tag_int_array
 * Signature: ([IJ)Lnet/minecraft/server/c/libnbt/NBTTag;
 */
JNIEXPORT jobject JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1new_1tag_1int_1array
  (JNIEnv *, jclass, jintArray, jlong);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_new_tag_long_array
 * Signature: ([JJ)Lnet/minecraft/server/c/libnbt/NBTTag;
 */
JNIEXPORT jobject JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1new_1tag_1long_1array
  (JNIEnv *, jclass, jlongArray, jlong);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_new_tag_short_array
 * Signature: ([SJ)Lnet/minecraft/server/c/libnbt/NBTTag;
 */
JNIEXPORT jobject JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1new_1tag_1short_1array
  (JNIEnv *, jclass, jshortArray, jlong);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_new_tag_float_array
 * Signature: ([FJ)Lnet/minecraft/server/c/libnbt/NBTTag;
 */
JNIEXPORT jobject JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1new_1tag_1float_1array
  (JNIEnv *, jclass, jfloatArray, jlong);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_new_tag_double_array
 * Signature: ([DJ)Lnet/minecraft/server/c/libnbt/NBTTag;
 */
JNIEXPORT jobject JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1new_1tag_1double_1array
  (JNIEnv *, jclass, jdoubleArray, jlong);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_new_tag_string_array
 * Signature: ([Ljava/lang/String;J)Lnet/minecraft/server/c/libnbt/NBTTag;
 */
JNIEXPORT jobject JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1new_1tag_1string_1array
  (JNIEnv *, jclass, jobjectArray, jlong);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_set_tag_name
 * Signature: (Lnet/minecraft/server/c/libnbt/NBTTag;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1set_1tag_1name
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_set_tag_name0
 * Signature: (Lnet/minecraft/server/c/libnbt/NBTTag;Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1set_1tag_1name0
  (JNIEnv *, jclass, jobject, jstring, jlong);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_tag_list_append
 * Signature: (Lnet/minecraft/server/c/libnbt/NBTTag;Lnet/minecraft/server/c/libnbt/NBTTag;)V
 */
JNIEXPORT void JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1tag_1list_1append
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_tag_list_get
 * Signature: (JJ)Lnet/minecraft/server/c/libnbt/NBTTag;
 */
JNIEXPORT jobject JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1tag_1list_1get
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_tag_compound_append
 * Signature: (Lnet/minecraft/server/c/libnbt/NBTTag;Lnet/minecraft/server/c/libnbt/NBTTag;)V
 */
JNIEXPORT void JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1tag_1compound_1append
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_tag_compound_get
 * Signature: (JLjava/lang/String;)Lnet/minecraft/server/c/libnbt/NBTTag;
 */
JNIEXPORT jobject JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1tag_1compound_1get
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     net_minecraft_server_c_libnbt_NBT
 * Method:    nbt_free_tag
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_minecraft_server_c_libnbt_NBT_nbt_1free_1tag
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
